Repository sibbay-ai/operating, pull requests merged in 2018-06, with the labels that each got.

#120 经期视频演示review
  经期演示视频review.md
Labels: ICP

#122 经期互动状态迁移文案
  经期互动状态迁移文案.md
Labels: ICP

#124 for #123 微信宣传
  feature/alisahuxu-微信宣传
Labels: approve

#119 6.1儿童节画设计
  ui_design/ertongjie/1
  ui_design/ertongjie/儿童节1.png
  ui_design/ertongjie/儿童节2.png
  ui_design/ertongjie/儿童节3.png
  ui_design/ertongjie/儿童节4.png
Labels: ICP, approve

#125 T恤设计
  ui_design/cloth design/002.ai
  ui_design/cloth design/cloth
Labels: ICP
