Repository sibbay-ai/operating, pull requests merged in 2018-04, with the labels that each got.

#84 for #81 Create greeting of April
  greeting everyday/greeting of April
Labels: ICP

#78 for #62，小白使用问题及建议
  copywriting/alisahuxu-小白健康使用问题及建议汇总
  小白使用问题及建议汇总.docx
Labels: ICP

#59 for#58，邀请页面设计
  001.png
  002.png
  003.png
  1111.png
  2222.png
  5.png
  777.png
  888.png
  999.png
Labels: size: 0.4

#83 for#79 清明节画制作
  5.png
Labels: ICP, approve

#73 for#68 一分钟认识小白健康-视频-第二稿
  1522046429077.jpg
Labels: ICP, approve, size: 0.1

#91 for #90 完善官网-内容
  alisahuxu-官网修订
Labels: ICP

#97 for#96 地球日画设计
  地球日01.png
  地球日02.png
  地球日03.png
  地球日04.png
Labels: ICP
