Repository sibbay-ai/operating, pull requests merged in 2018-03, with the labels that each got.

#54 for#52，设计女神节闪图
  未标题-1.png
  未标题-2.png
  未标题-3.png
  未标题-4.png
Labels: size: 0.1

#53 for#25，年会名单
  list new year.xls
Labels: ICP, approve, size: 0.2

#64 for#63，视频初稿
  图片 1.png
Labels: review, size: 0.1

#70 for #69，地球一小时画
  1.png
  2.png
  3.png
  4.png
Labels: review, size: 0.1

#71 for#60，文章修改润色
  巧用中医妙招防流感---修改版本.md
Labels: review, size: 0.1

#76 for#72，例假管理文案提交
  例假管理bunch1-经期定位.md
  例假管理bunch2.md
  例假管理bunch3经期结束建议.md
Labels: approve, review, size: 0.1
